replicaCount: 1

image:
  repository: "michalschott/go-ws"
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext: {}

securityContext: {}

readinessProbe:
  enabled: true
  path: "/"
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  enabled: true
  path: "/"
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3
